# Importing data an libraries:

In [1]:
# Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# data
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

# Filling Missing Data:

## 1. Train

In [3]:
train

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1,customer_category
0,csid_1,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,C,F,0
1,csid_2,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,C,A,0
2,csid_3,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,C,BA,0
3,csid_4,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,AA,F,0
4,csid_5,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,C,AA,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10733,csid_10734,23.672615,6.701514,0.092879,-0.017332,1.210397,7.003663,3.027084,1.952911,C,BA,0
10734,csid_10735,25.673028,6.497796,0.050216,-0.047211,0.725230,5.407507,3.104172,5.124286,C,BA,0
10735,csid_10736,31.676844,7.799880,0.062961,-0.032765,0.318118,5.598486,2.403051,21.864188,A,BA,0
10736,csid_10737,28.441780,5.588302,-0.093931,0.081586,0.132177,3.616492,4.972243,86.969977,B,AA,0
10737,csid_10738,20.663035,4.478301,0.253165,0.381349,0.504904,4.181092,4.469215,27.770899,B,A,0

In [4]:
train.describe()

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_category
count,10738.000000,10696.000000,10738.000000,10701.000000,10738.000000,10692.000000,10672.000000,10738.000000,10738.000000
mean,19.060941,5.274847,0.175912,0.374230,2.376895,5.788180,3.150071,17.061836,0.120600
std,7.419609,1.882559,0.372829,1.222031,5.601911,2.531309,1.035416,18.762693,0.325677
min,0.568965,-0.161940,-0.547989,-0.462494,0.028575,2.752836,0.363338,-0.486834,0.000000
25%,13.518021,3.971587,0.010840,-0.027666,0.313610,4.193234,2.454017,4.530085,0.000000
50%,18.774109,5.218479,0.074078,0.037201,0.516830,4.842575,3.118394,12.653357,0.000000
75%,24.501719,6.520364,0.159606,0.179029,1.125380,6.286400,3.756566,23.114577,0.000000
max,47.306691,16.638243,2.679474,14.701914,52.395014,18.743836,9.090206,248.552755,1.000000

In [5]:
train.isna().sum()

customer_id                          0
customer_visit_score                 0
customer_product_search_score       42
customer_ctr_score                   0
customer_stay_score                 37
customer_frequency_score             0
customer_product_variation_score    46
customer_order_score                66
customer_affinity_score              0
customer_active_segment             23
X1                                  37
customer_category                    0
dtype: int64

In [6]:
tr = train.copy()
te = test.copy()

In [7]:
tr['customer_product_search_score'].fillna(tr['customer_product_search_score'].mean(),inplace=True)
tr['customer_stay_score'].fillna(tr['customer_stay_score'].mean(),inplace=True)
tr['customer_product_variation_score'].fillna(tr['customer_product_variation_score'].median(),inplace=True)
tr['customer_order_score'].fillna(tr['customer_order_score'].median(),inplace=True)

In [8]:
tr

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1,customer_category
0,csid_1,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,C,F,0
1,csid_2,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,C,A,0
2,csid_3,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,C,BA,0
3,csid_4,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,AA,F,0
4,csid_5,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,C,AA,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10733,csid_10734,23.672615,6.701514,0.092879,-0.017332,1.210397,7.003663,3.027084,1.952911,C,BA,0
10734,csid_10735,25.673028,6.497796,0.050216,-0.047211,0.725230,5.407507,3.104172,5.124286,C,BA,0
10735,csid_10736,31.676844,7.799880,0.062961,-0.032765,0.318118,5.598486,2.403051,21.864188,A,BA,0
10736,csid_10737,28.441780,5.588302,-0.093931,0.081586,0.132177,3.616492,4.972243,86.969977,B,AA,0
10737,csid_10738,20.663035,4.478301,0.253165,0.381349,0.504904,4.181092,4.469215,27.770899,B,A,0

In [9]:
tr.isna().sum()

customer_id                          0
customer_visit_score                 0
customer_product_search_score        0
customer_ctr_score                   0
customer_stay_score                  0
customer_frequency_score             0
customer_product_variation_score     0
customer_order_score                 0
customer_affinity_score              0
customer_active_segment             23
X1                                  37
customer_category                    0
dtype: int64

In [10]:
tr1 = tr.copy()

In [11]:
tr['customer_visit_score'][1]

17.092978802911414

In [12]:
for i in range(len(tr1['customer_visit_score'])):
    if tr1['customer_active_segment'][i] is np.nan:
        if tr1['customer_visit_score'][i] <= 10:
            tr1['customer_active_segment'][i] =  'D'
        elif tr1['customer_visit_score'][i] > 10 and tr1['customer_visit_score'][i] <= 30:
            tr1['customer_active_segment'][i] = 'B'
        elif tr1['customer_visit_score'][i] >= 30:
            tr1['customer_active_segment'][i] = 'AA'
    else:
        pass

In [13]:
tr1.isna().sum()

customer_id                          0
customer_visit_score                 0
customer_product_search_score        0
customer_ctr_score                   0
customer_stay_score                  0
customer_frequency_score             0
customer_product_variation_score     0
customer_order_score                 0
customer_affinity_score              0
customer_active_segment              0
X1                                  37
customer_category                    0
dtype: int64

In [14]:
tr1['X1'].value_counts()

BA    4511
A     2268
F     2235
AA    1611
E       76
Name: X1, dtype: int64

In [15]:
for i in range(len(tr1['customer_order_score'])):
    if tr1['X1'][i] is np.nan:
        if tr1['customer_order_score'][i] <= 3 and tr1['customer_order_score'][i] >2:
            tr1['X1'][i] =  'BA'
        if tr1['customer_order_score'][i] <= 2:
            tr1['X1'][i] =  'F'
        elif tr1['customer_order_score'][i] <= 4 and tr1['customer_visit_score'][i] > 3:
            tr1['X1'][i] = 'A'
        elif tr1['customer_order_score'][i] > 4 and tr1['customer_visit_score'][i] <= 6:
            tr1['X1'][i] = 'AA'
        elif tr1['customer_order_score'][i] > 6:
            tr1['X1'][i] = 'E'
    else:
        pass

In [16]:
tr1.isna().sum()

customer_id                         0
customer_visit_score                0
customer_product_search_score       0
customer_ctr_score                  0
customer_stay_score                 0
customer_frequency_score            0
customer_product_variation_score    0
customer_order_score                0
customer_affinity_score             0
customer_active_segment             0
X1                                  6
customer_category                   0
dtype: int64

In [17]:
tr1['X1'].fillna('A',inplace=True)

In [18]:
tr1.isna().sum()

customer_id                         0
customer_visit_score                0
customer_product_search_score       0
customer_ctr_score                  0
customer_stay_score                 0
customer_frequency_score            0
customer_product_variation_score    0
customer_order_score                0
customer_affinity_score             0
customer_active_segment             0
X1                                  0
customer_category                   0
dtype: int64

## 2. Test

In [19]:
te

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
0,csid_10739,22.500174,3.702145,0.118811,0.093253,0.689237,5.786842,3.748009,7.661716,B,BA
1,csid_10740,13.225950,3.600102,0.130985,0.053575,0.142756,3.940359,3.469659,33.999679,B,AA
2,csid_10741,14.603376,5.084047,-0.004651,-0.036299,0.333709,4.254662,3.855939,33.485630,B,AA
3,csid_10742,26.149905,3.025501,0.229740,0.204591,3.768405,6.942625,2.362421,0.795372,B,BA
4,csid_10743,19.810630,5.020400,-0.011347,-0.028780,0.286841,4.585513,3.278624,15.052058,C,BA
...,...,...,...,...,...,...,...,...,...,...,...
7155,csid_17894,18.164300,7.240835,-0.056238,-0.177289,0.336608,4.043067,4.758199,68.052717,C,AA
7156,csid_17895,25.363705,4.881059,0.038720,0.054397,2.452571,7.582251,1.823892,2.080245,C,BA
7157,csid_17896,11.160720,5.019859,0.053864,-0.102337,4.968183,8.585355,2.422193,0.616082,C,BA
7158,csid_17897,17.140020,9.269037,0.059911,-0.004299,0.357399,4.193971,3.715392,26.939493,C,BA
7159,csid_17898,10.698835,12.173331,0.475469,0.014124,23.358252,10.805826,1.571717,0.133973,B,BA

In [20]:
te.describe()

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score
count,7160.000000,7131.000000,7160.000000,7144.000000,7160.000000,7117.000000,7119.000000,7160.000000
mean,19.700385,5.385970,0.111038,0.202822,1.885588,5.444226,3.309440,19.889035
std,6.980932,1.779850,0.260733,0.886824,4.967213,2.336244,1.060144,20.783679
min,1.248385,-0.113791,-0.615134,-0.381836,0.022957,2.718819,0.620935,-0.501215
25%,14.250243,4.146965,0.005032,-0.033382,0.282119,4.099106,2.645399,6.910150
50%,19.256051,5.358104,0.063178,0.024508,0.457636,4.669433,3.254096,14.630477
75%,24.756843,6.579949,0.135072,0.130086,0.822750,5.665742,3.875797,26.102862
max,42.960500,13.678108,2.528584,13.533233,49.683739,19.095799,11.388305,257.251810

In [21]:
te.isna().sum()

customer_id                          0
customer_visit_score                 0
customer_product_search_score       29
customer_ctr_score                   0
customer_stay_score                 16
customer_frequency_score             0
customer_product_variation_score    43
customer_order_score                41
customer_affinity_score              0
customer_active_segment             12
X1                                  25
dtype: int64

In [22]:
te['customer_product_search_score'].fillna(te['customer_product_search_score'].mean(),inplace=True)
te['customer_stay_score'].fillna(te['customer_stay_score'].mean(),inplace=True)
te['customer_product_variation_score'].fillna(te['customer_product_variation_score'].median(),inplace=True)
te['customer_order_score'].fillna(te['customer_order_score'].median(),inplace=True)

In [23]:
te.isna().sum()

customer_id                          0
customer_visit_score                 0
customer_product_search_score        0
customer_ctr_score                   0
customer_stay_score                  0
customer_frequency_score             0
customer_product_variation_score     0
customer_order_score                 0
customer_affinity_score              0
customer_active_segment             12
X1                                  25
dtype: int64

In [24]:
te1 = te.copy()

In [25]:
for i in range(len(te1['customer_order_score'])):
    if te1['X1'][i] is np.nan:
        if te1['customer_order_score'][i] <= 3 and te1['customer_order_score'][i] >2:
            te1['X1'][i] =  'BA'
        if te1['customer_order_score'][i] <= 2:
            te1['X1'][i] =  'F'
        elif te1['customer_order_score'][i] <= 4 and te1['customer_visit_score'][i] > 3:
            te1['X1'][i] = 'A'
        elif te1['customer_order_score'][i] > 4 and te1['customer_visit_score'][i] <= 6:
            te1['X1'][i] = 'AA'
        elif te1['customer_order_score'][i] > 6:
            te1['X1'][i] = 'E'
    else:
        pass

In [26]:
te1.isna().sum()

customer_id                          0
customer_visit_score                 0
customer_product_search_score        0
customer_ctr_score                   0
customer_stay_score                  0
customer_frequency_score             0
customer_product_variation_score     0
customer_order_score                 0
customer_affinity_score              0
customer_active_segment             12
X1                                   4
dtype: int64

In [27]:
te1[te1['X1'].isna()]

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
438,csid_11177,7.210271,2.891116,0.300415,0.202822,0.202760,4.266486,4.423772,35.923575,C,NaN
1270,csid_12009,16.536471,7.153502,0.147622,-0.112374,0.495643,3.686297,4.270297,21.787479,B,NaN
2465,csid_13204,24.949798,2.907471,0.103941,0.151400,0.298304,4.546212,4.000319,18.172958,C,NaN
6880,csid_17619,23.057634,2.599330,0.186959,0.207863,0.402761,5.155971,4.054868,21.525141,C,NaN

In [28]:
te1['X1'].fillna('A',inplace=True)

In [29]:
te1.isna().sum()

customer_id                          0
customer_visit_score                 0
customer_product_search_score        0
customer_ctr_score                   0
customer_stay_score                  0
customer_frequency_score             0
customer_product_variation_score     0
customer_order_score                 0
customer_affinity_score              0
customer_active_segment             12
X1                                   0
dtype: int64

In [30]:
for i in range(len(te1['customer_visit_score'])):
    if te1['customer_active_segment'][i] is np.nan:
        if te1['customer_visit_score'][i] <= 10:
            te1['customer_active_segment'][i] =  'D'
        elif te1['customer_visit_score'][i] > 10 and te1['customer_visit_score'][i] <= 30:
            te1['customer_active_segment'][i] = 'B'
        elif te1['customer_visit_score'][i] >= 30:
            te1['customer_active_segment'][i] = 'AA'
    else:
        pass

In [31]:
te1.isna().sum()

customer_id                         0
customer_visit_score                0
customer_product_search_score       0
customer_ctr_score                  0
customer_stay_score                 0
customer_frequency_score            0
customer_product_variation_score    0
customer_order_score                0
customer_affinity_score             0
customer_active_segment             0
X1                                  0
dtype: int64

# Now Some Data conversion:

## 1. train

In [32]:
tr1

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1,customer_category
0,csid_1,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,C,F,0
1,csid_2,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,C,A,0
2,csid_3,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,C,BA,0
3,csid_4,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,AA,F,0
4,csid_5,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,C,AA,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10733,csid_10734,23.672615,6.701514,0.092879,-0.017332,1.210397,7.003663,3.027084,1.952911,C,BA,0
10734,csid_10735,25.673028,6.497796,0.050216,-0.047211,0.725230,5.407507,3.104172,5.124286,C,BA,0
10735,csid_10736,31.676844,7.799880,0.062961,-0.032765,0.318118,5.598486,2.403051,21.864188,A,BA,0
10736,csid_10737,28.441780,5.588302,-0.093931,0.081586,0.132177,3.616492,4.972243,86.969977,B,AA,0
10737,csid_10738,20.663035,4.478301,0.253165,0.381349,0.504904,4.181092,4.469215,27.770899,B,A,0

In [33]:
tr1['customer_active_segment'].value_counts()

C     4919
B     4448
D      538
AA     421
A      412
Name: customer_active_segment, dtype: int64

In [34]:
tr2 = tr1.copy()

In [35]:
tr2['customer_active_segment'] = tr2['customer_active_segment'].map({'C':4, 'B':2, 'D':3, 'AA':1, 'A':0})

In [36]:
tr2

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1,customer_category
0,csid_1,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,4,F,0
1,csid_2,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,4,A,0
2,csid_3,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,4,BA,0
3,csid_4,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,1,F,0
4,csid_5,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,4,AA,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10733,csid_10734,23.672615,6.701514,0.092879,-0.017332,1.210397,7.003663,3.027084,1.952911,4,BA,0
10734,csid_10735,25.673028,6.497796,0.050216,-0.047211,0.725230,5.407507,3.104172,5.124286,4,BA,0
10735,csid_10736,31.676844,7.799880,0.062961,-0.032765,0.318118,5.598486,2.403051,21.864188,0,BA,0
10736,csid_10737,28.441780,5.588302,-0.093931,0.081586,0.132177,3.616492,4.972243,86.969977,2,AA,0
10737,csid_10738,20.663035,4.478301,0.253165,0.381349,0.504904,4.181092,4.469215,27.770899,2,A,0

In [37]:
tr2['X1'] = tr2['X1'].map({'F':4, 'AA':1, 'BA':3, 'E':0, 'A':2})

In [38]:
tr2

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1,customer_category
0,csid_1,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,4,4,0
1,csid_2,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,4,2,0
2,csid_3,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,4,3,0
3,csid_4,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,1,4,0
4,csid_5,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10733,csid_10734,23.672615,6.701514,0.092879,-0.017332,1.210397,7.003663,3.027084,1.952911,4,3,0
10734,csid_10735,25.673028,6.497796,0.050216,-0.047211,0.725230,5.407507,3.104172,5.124286,4,3,0
10735,csid_10736,31.676844,7.799880,0.062961,-0.032765,0.318118,5.598486,2.403051,21.864188,0,3,0
10736,csid_10737,28.441780,5.588302,-0.093931,0.081586,0.132177,3.616492,4.972243,86.969977,2,1,0
10737,csid_10738,20.663035,4.478301,0.253165,0.381349,0.504904,4.181092,4.469215,27.770899,2,2,0

## 2. test

In [39]:
te1

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
0,csid_10739,22.500174,3.702145,0.118811,0.093253,0.689237,5.786842,3.748009,7.661716,B,BA
1,csid_10740,13.225950,3.600102,0.130985,0.053575,0.142756,3.940359,3.469659,33.999679,B,AA
2,csid_10741,14.603376,5.084047,-0.004651,-0.036299,0.333709,4.254662,3.855939,33.485630,B,AA
3,csid_10742,26.149905,3.025501,0.229740,0.204591,3.768405,6.942625,2.362421,0.795372,B,BA
4,csid_10743,19.810630,5.020400,-0.011347,-0.028780,0.286841,4.585513,3.278624,15.052058,C,BA
...,...,...,...,...,...,...,...,...,...,...,...
7155,csid_17894,18.164300,7.240835,-0.056238,-0.177289,0.336608,4.043067,4.758199,68.052717,C,AA
7156,csid_17895,25.363705,4.881059,0.038720,0.054397,2.452571,7.582251,1.823892,2.080245,C,BA
7157,csid_17896,11.160720,5.019859,0.053864,-0.102337,4.968183,8.585355,2.422193,0.616082,C,BA
7158,csid_17897,17.140020,9.269037,0.059911,-0.004299,0.357399,4.193971,3.715392,26.939493,C,BA
7159,csid_17898,10.698835,12.173331,0.475469,0.014124,23.358252,10.805826,1.571717,0.133973,B,BA

In [40]:
te2 = te1.copy()

In [41]:
te2['customer_active_segment'] = te2['customer_active_segment'].map({'C':4, 'B':2, 'D':3, 'AA':1, 'A':0})

In [42]:
te2

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
0,csid_10739,22.500174,3.702145,0.118811,0.093253,0.689237,5.786842,3.748009,7.661716,2,BA
1,csid_10740,13.225950,3.600102,0.130985,0.053575,0.142756,3.940359,3.469659,33.999679,2,AA
2,csid_10741,14.603376,5.084047,-0.004651,-0.036299,0.333709,4.254662,3.855939,33.485630,2,AA
3,csid_10742,26.149905,3.025501,0.229740,0.204591,3.768405,6.942625,2.362421,0.795372,2,BA
4,csid_10743,19.810630,5.020400,-0.011347,-0.028780,0.286841,4.585513,3.278624,15.052058,4,BA
...,...,...,...,...,...,...,...,...,...,...,...
7155,csid_17894,18.164300,7.240835,-0.056238,-0.177289,0.336608,4.043067,4.758199,68.052717,4,AA
7156,csid_17895,25.363705,4.881059,0.038720,0.054397,2.452571,7.582251,1.823892,2.080245,4,BA
7157,csid_17896,11.160720,5.019859,0.053864,-0.102337,4.968183,8.585355,2.422193,0.616082,4,BA
7158,csid_17897,17.140020,9.269037,0.059911,-0.004299,0.357399,4.193971,3.715392,26.939493,4,BA
7159,csid_17898,10.698835,12.173331,0.475469,0.014124,23.358252,10.805826,1.571717,0.133973,2,BA

In [43]:
te2['X1'] = te2['X1'].map({'F':4, 'AA':1, 'BA':3, 'E':0, 'A':2})

In [44]:
te2

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
0,csid_10739,22.500174,3.702145,0.118811,0.093253,0.689237,5.786842,3.748009,7.661716,2,3
1,csid_10740,13.225950,3.600102,0.130985,0.053575,0.142756,3.940359,3.469659,33.999679,2,1
2,csid_10741,14.603376,5.084047,-0.004651,-0.036299,0.333709,4.254662,3.855939,33.485630,2,1
3,csid_10742,26.149905,3.025501,0.229740,0.204591,3.768405,6.942625,2.362421,0.795372,2,3
4,csid_10743,19.810630,5.020400,-0.011347,-0.028780,0.286841,4.585513,3.278624,15.052058,4,3
...,...,...,...,...,...,...,...,...,...,...,...
7155,csid_17894,18.164300,7.240835,-0.056238,-0.177289,0.336608,4.043067,4.758199,68.052717,4,1
7156,csid_17895,25.363705,4.881059,0.038720,0.054397,2.452571,7.582251,1.823892,2.080245,4,3
7157,csid_17896,11.160720,5.019859,0.053864,-0.102337,4.968183,8.585355,2.422193,0.616082,4,3
7158,csid_17897,17.140020,9.269037,0.059911,-0.004299,0.357399,4.193971,3.715392,26.939493,4,3
7159,csid_17898,10.698835,12.173331,0.475469,0.014124,23.358252,10.805826,1.571717,0.133973,2,3

# Data formation:

In [45]:
tr2

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1,customer_category
0,csid_1,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,4,4,0
1,csid_2,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,4,2,0
2,csid_3,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,4,3,0
3,csid_4,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,1,4,0
4,csid_5,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10733,csid_10734,23.672615,6.701514,0.092879,-0.017332,1.210397,7.003663,3.027084,1.952911,4,3,0
10734,csid_10735,25.673028,6.497796,0.050216,-0.047211,0.725230,5.407507,3.104172,5.124286,4,3,0
10735,csid_10736,31.676844,7.799880,0.062961,-0.032765,0.318118,5.598486,2.403051,21.864188,0,3,0
10736,csid_10737,28.441780,5.588302,-0.093931,0.081586,0.132177,3.616492,4.972243,86.969977,2,1,0
10737,csid_10738,20.663035,4.478301,0.253165,0.381349,0.504904,4.181092,4.469215,27.770899,2,2,0

In [46]:
X = tr2.drop(['customer_id', 'customer_category'],1)

In [47]:
X

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
0,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,4,4
1,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,4,2
2,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,4,3
3,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,1,4
4,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,4,1
...,...,...,...,...,...,...,...,...,...,...
10733,23.672615,6.701514,0.092879,-0.017332,1.210397,7.003663,3.027084,1.952911,4,3
10734,25.673028,6.497796,0.050216,-0.047211,0.725230,5.407507,3.104172,5.124286,4,3
10735,31.676844,7.799880,0.062961,-0.032765,0.318118,5.598486,2.403051,21.864188,0,3
10736,28.441780,5.588302,-0.093931,0.081586,0.132177,3.616492,4.972243,86.969977,2,1
10737,20.663035,4.478301,0.253165,0.381349,0.504904,4.181092,4.469215,27.770899,2,2

In [48]:
Y = tr2['customer_category']

In [49]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
10733    0
10734    0
10735    0
10736    0
10737    0
Name: customer_category, Length: 10738, dtype: int64

In [50]:
te2

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
0,csid_10739,22.500174,3.702145,0.118811,0.093253,0.689237,5.786842,3.748009,7.661716,2,3
1,csid_10740,13.225950,3.600102,0.130985,0.053575,0.142756,3.940359,3.469659,33.999679,2,1
2,csid_10741,14.603376,5.084047,-0.004651,-0.036299,0.333709,4.254662,3.855939,33.485630,2,1
3,csid_10742,26.149905,3.025501,0.229740,0.204591,3.768405,6.942625,2.362421,0.795372,2,3
4,csid_10743,19.810630,5.020400,-0.011347,-0.028780,0.286841,4.585513,3.278624,15.052058,4,3
...,...,...,...,...,...,...,...,...,...,...,...
7155,csid_17894,18.164300,7.240835,-0.056238,-0.177289,0.336608,4.043067,4.758199,68.052717,4,1
7156,csid_17895,25.363705,4.881059,0.038720,0.054397,2.452571,7.582251,1.823892,2.080245,4,3
7157,csid_17896,11.160720,5.019859,0.053864,-0.102337,4.968183,8.585355,2.422193,0.616082,4,3
7158,csid_17897,17.140020,9.269037,0.059911,-0.004299,0.357399,4.193971,3.715392,26.939493,4,3
7159,csid_17898,10.698835,12.173331,0.475469,0.014124,23.358252,10.805826,1.571717,0.133973,2,3

In [51]:
te2_test = te2.drop('customer_id',1)

In [52]:
te2_test

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
0,22.500174,3.702145,0.118811,0.093253,0.689237,5.786842,3.748009,7.661716,2,3
1,13.225950,3.600102,0.130985,0.053575,0.142756,3.940359,3.469659,33.999679,2,1
2,14.603376,5.084047,-0.004651,-0.036299,0.333709,4.254662,3.855939,33.485630,2,1
3,26.149905,3.025501,0.229740,0.204591,3.768405,6.942625,2.362421,0.795372,2,3
4,19.810630,5.020400,-0.011347,-0.028780,0.286841,4.585513,3.278624,15.052058,4,3
...,...,...,...,...,...,...,...,...,...,...
7155,18.164300,7.240835,-0.056238,-0.177289,0.336608,4.043067,4.758199,68.052717,4,1
7156,25.363705,4.881059,0.038720,0.054397,2.452571,7.582251,1.823892,2.080245,4,3
7157,11.160720,5.019859,0.053864,-0.102337,4.968183,8.585355,2.422193,0.616082,4,3
7158,17.140020,9.269037,0.059911,-0.004299,0.357399,4.193971,3.715392,26.939493,4,3
7159,10.698835,12.173331,0.475469,0.014124,23.358252,10.805826,1.571717,0.133973,2,3

# Model Selection:

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import svm

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,stratify=Y)

In [56]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.979050279329609

In [57]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.972998137802607

In [58]:
dt = DecisionTreeRegressor()
dt.fit(X_train,y_train)
dt.score(X_test,y_test)

0.6092557807751031

In [59]:
gb = GradientBoostingClassifier()
gb.fit(X_train,y_train)
gb.score(X_test,y_test)

0.9762569832402235

In [60]:
sv = svm.SVC()
sv.fit(X_train,y_train)
sv.score(X_test,y_test)

0.9594972067039106

# Predictions:

## 1. Random Forest:

In [61]:
#prediction = rf.predict(te2_test)

In [62]:
#prediction

In [63]:
#data = pd.DataFrame({'customer_id':test['customer_id'], 'customer_category':prediction})

In [64]:
#data

In [65]:
#data['customer_category'].value_counts()

In [66]:
# Exporting our prediction data to csv file
#data.to_csv('Submission5.csv',index=False)

## 2. Logistic regression:

In [67]:
prediction1 = lr.predict(te2_test)

In [68]:
prediction1

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [69]:
data1 = pd.DataFrame({'customer_id':test['customer_id'], 'customer_category':prediction1})

In [70]:
data1

     customer_id  customer_category
0     csid_10739                  0
1     csid_10740                  0
2     csid_10741                  0
3     csid_10742                  0
4     csid_10743                  0
...          ...                ...
7155  csid_17894                  0
7156  csid_17895                  0
7157  csid_17896                  0
7158  csid_17897                  0
7159  csid_17898                  1

[7160 rows x 2 columns]

In [71]:
data1['customer_category'].value_counts()

0    6846
1     314
Name: customer_category, dtype: int64

In [72]:
# Exporting our prediction data to csv file
data1.to_csv('Submission15.csv',index=False)